Repository Avanti-Bootcamp-GET-Geeks/GetEvents, pull requests merged in 2024-05, with the labels that each got.

#18 CRUD Categorias
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Global.css
  src/assets/img/logo.svg
  src/assets/img/lupa.svg
  src/components/footer/Footer.jsx
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/pages/private/categories/Categories.jsx
  src/pages/private/settings/Settings.jsx
  src/pages/public/home/Home.jsx
  src/pages/public/login/Login.jsx
  src/pages/public/register/Register.jsx
  src/services/categoryService.jsx
  src/services/eventService.jsx
Labels: enhancement

#19 17 context e rota privada
  src/context/AuthContext.jsx
  src/hooks/useAuth.jsx
  src/pages/public/login/Login.jsx
  src/routes/ProtectedRoute.jsx
  src/services/authService.jsx
  src/services/userService.jsx
Labels: enhancement

#22 Search event
  src/App.jsx
  src/components/header/Header.jsx
  src/context/SearchContext.jsx
  src/hooks/useAuth.jsx
  src/hooks/useSearch.jsx
  src/pages/private/events/CreateEvent.jsx
  src/pages/private/events/UpdateEvent.jsx
  src/pages/public/home/Home.jsx
Labels: enhancement

#21 Página de cadastro
  package-lock.json
  package.json
  src/pages/public/register/Register.jsx
  src/services/roleService.jsx
Labels: enhancement

#24 Cargos
  src/pages/private/roles/Roles.jsx
  src/routes/PrivateRoutes.jsx
  src/services/roleService.jsx
Labels: enhancement

#26 refactor: Register e remove react-input-mask
  package-lock.json
  package.json
  src/pages/private/roles/Roles.jsx
  src/pages/public/register/Register.jsx
Labels: enhancement

#25 Componente Header e Página Settings
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/Global.css
  src/assets/img/logo.svg
  src/components/card/Card.css
  src/components/eventList/EventList.css
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/pages/private/categories/Categories.jsx
  src/pages/private/settings/Settings.jsx
  src/pages/public/eventInfo/EventInfo.css
  src/pages/public/login/Login.jsx
Labels: enhancement

#29 Local
  package-lock.json
  src/components/header/Header.jsx
  src/components/pagination/Paginationn.jsx
  src/pages/private/locations/Locations.jsx
  src/pages/private/roles/Roles.jsx
  src/routes/PrivateRoutes.jsx
Labels: enhancement

#37 Ajustes tamanho de imagens, menu, favicon
  index.html
  public/vite.svg
  src/App.css
  src/components/header/Header.css
  src/components/header/Header.jsx
  src/pages/private/settings/Settings.jsx
  src/pages/public/eventInfo/EventInfo.css
  src/pages/public/eventInfo/EventInfo.jsx
Labels: bug, enhancement

#36 feat: Pesquisa por CEP no cadastro de locais e novos icons na página.
  src/pages/private/locations/Locations.jsx
  src/services/apiCep.jsx
  src/services/localService.jsx
Labels: enhancement

#41 Doc readme
  LICENSE
  README.md
  src/assets/img/screen/admin-menu.png
  src/assets/img/screen/admin.png
  src/assets/img/screen/cadastrar-evento.png
  src/assets/img/screen/cadastro.png
  src/assets/img/screen/categoria-associada.png
  src/assets/img/screen/categorias.png
  src/assets/img/screen/confirma-exclusao.png
  src/assets/img/screen/criar-categoria.png
  src/assets/img/screen/criar-local.png
  src/assets/img/screen/editar-categoria.png
  src/assets/img/screen/editar-evento.png
  src/assets/img/screen/editar-local.png
  src/assets/img/screen/evento.png
  src/assets/img/screen/exclusao-categoria.png
  src/assets/img/screen/home-publica.png
  src/assets/img/screen/home.png
  src/assets/img/screen/locais.png
  src/assets/img/screen/local-associado.png
  src/assets/img/screen/login.png
  src/assets/img/screen/meus-eventos.png
  src/assets/img/screen/organizador.png
  src/assets/img/screen/usuario-minha-conta.png
  src/assets/img/screen/usuarios-menu.png
  src/assets/img/screen/visitante.png
  src/components/footer/Footer.css
Labels: documentation

#43 Validações
  src/pages/private/roles/Roles.jsx
  src/pages/public/register/Register.jsx
Labels: enhancement
